### ISSUE TITLE
Issues with partially matching language codes.

### ISSUE THREAD

**Issue by imnasnainaec** [sillsdev/mui-language-picker#2]
I am testing The Combine with a project that uses `zh-CN-x-pyn`, but when I select `zh-CN`, the result is `zh-CN-CN-x-pyn`.

The project also has `zhn-fonipa` but since there is no `zhn`, I can only go with `zhn-Hani-fonipa` or `zh-Latn-fonipa`, neither of which is accurate.

**Comment by gtryus** [comment]
ok, thanks for the message. I'll see what I can do about looking in this.

**Comment by gtryus** [comment]
ok, I fixed the first one (but haven't published it yet). The second one is the one I am trying to understand. langtags.json has two codes: zhn-Hani and zhn-Latn. It doesn't have a zhn (without specifying a script). So fonipa is a variant. So technically, either zhn-Hani-fonipa or zhn-Latn-fonipa is correct  and either is the shortest possible code since zhn has no default script, using that code without a script is not allowed. In fact ipa is an extended Latin script so zhn-Latn-fonipa is probably more correct than zhn-Hani-fonipa. I will do more checking but publish the solution to the first issue and treat the second one as "working as designed" until I get more clarification on this issue. Do you have a resource that shows that zhn-fonipa is a valid code?

**Comment by imnasnainaec** [comment]
Thanks! The first one was more clearly an issue to me. I wasn't as sure about the second--it's a code somebody used, but I don't know its origins in the data, so I can't speak to whether it is valid.

**Comment by gtryus** [comment]
Ok, Martin pointed me to: https://github.com/silnrsi/langtags/blob/master/doc/langtags.md#variants-field which explains the logic on the variants field. So I will work on supporting zhn-fonapi

**Comment by imnasnainaec** [comment]
Now the options are `zhn`, `zhn-Hani`, and `zhn-fonipa`, but if you select fonipa then go back to Latn, it's stuck on `zhn-fonipa`.

**Comment by gtryus** [comment]
This correctly returns the options now.
